In [20]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [21]:
URL = "https://www.espn.com/nba/player/stats/_/id/1966/seasontype/3/lebron-james"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}
page = requests.get(URL, headers=headers)
pageSoup = BeautifulSoup(page.content, 'html.parser')

print(pageSoup.text)

LeBron James Career Stats - NBA Postseason - ESPN































Skip to main contentSkip to navigationESPNNFLNFLNBANBAMLBMLBNHLNHLSoccerSoccerGolfGolfMore SportsMore SportsESPN PlusESPN BETWatchWatchFantasyFantasyMore ESPNMore ESPNSearchLeBronJamesLos Angeles Lakers#23Small ForwardFollowHT/WT6' 9", 250 lbsBirthdate12/30/1984 (39)Draft Info2003: Rd 1, Pk 1 (CLE)StatusActiveExperience20th Season2023-24 season statsPTS25.713thREB7.332ndAST8.35thFG%54.020thOverviewNewsStatsBioSplitsGame LogAdvanced StatsStatsRegular SeasonPostseasonhiddenPostseason AveragesseasonTeam2005-06CLE2006-07CLE2007-08CLE2008-09CLE2009-10CLE2010-11MIA2011-12MIA2012-13MIA2013-14MIA2014-15CLE2015-16CLE2016-17CLE2017-18CLE2019-20LAL2020-21LAL2022-23LAL2023-24LALCareerGPGSMINFGFG%3PT3P%FTFT%ORDRREBASTBLKSTLPFTOPTS131346.511.2-23.647.61.6-4.833.36.7-9.173.71.76.48.15.80.71.43.45.030.8202044.78.3-20.041.61.1-3.828.07.4-9.875.51.36.88.18.00.51.72.03.325.1131342.58.7-21.241.11.4-5.425.79.4-12.873.11.26.67.87.61.31.82.54.228.2141441.411.4-22.351.01.9-5.833.310.6-14.274.91.47.89.17.30.91.62.12.735.3111141.89.6-19.250.21.8-4.540.08.0-10.973.31.47.99.37.61.81.72.13.829.1212143.98.3-17.846.61.4-4.035.35.7-7.476.31.66.88.45.91.21.72.73.123.7232342.710.9-21.850.01.0-3.725.97.5-10.273.92.37.49.75.60.71.92.03.530.3232341.79.2-18.849.11.6-4.237.55.9-7.677.71.66.88.46.60.81.81.93.025.9202038.29.6-17.056.51.8-4.340.76.5-8.080.60.76.47.14.80.61.82.33.127.4202042.211.4-27.241.71.3-5.522.76.1-8.473.11.99.511.38.51.11.72.94.130.1212139.110.4-19.952.51.5-4.534.03.9-5.966.12.07.59.57.61.32.32.63.626.3181841.312.1-21.356.52.4-5.941.16.3-9.069.81.18.19.17.81.31.92.44.032.8222241.912.5-23.253.91.8-5.234.27.2-9.774.61.47.79.19.01.01.42.44.334.0212136.310.2-18.256.02.1-5.737.05.1-7.172.01.39.410.88.80.91.21.94.027.66637.39.0-19.047.43.0-8.037.52.3-3.860.91.26.07.28.00.31.51.24.223.3161638.79.2-18.449.81.8-6.626.44.4-5.876.11.68.39.96.51.11.11.82.524.55540.811.2-19.856.62.0-5.238.53.4-4.673.90.86.06.88.81.02.42.23.827.828728741.310.2-20.549.71.6-4.933.26.4-8.674.11.57.59.07.21.01.72.33.628.4Postseason TotalsseasonTeam2005-06CLE2006-07CLE2007-08CLE2008-09CLE2009-10CLE2010-11MIA2011-12MIA2012-13MIA2013-14MIA2014-15CLE2015-16CLE2016-17CLE2017-18CLE2019-20LAL2020-21LAL2022-23LAL2023-24LALCareerFGFG%3PT3P%FTFT%ORDRREBASTBLKSTLPFTOPTS146-30747.621-6333.387-11873.72283105769184465400166-39941.621-7528.0148-19675.52613516115910344066501113-27541.118-7025.7122-16773.116861029917233354366159-31251.027-8133.3149-19974.91910912810212233038494106-21150.220-5040.088-12073.315871028420192342320174-37346.630-8535.3119-15676.33414217612325355666497251-50250.022-8525.9173-23473.95417022412916434781697212-43249.136-9637.5136-17577.73715619315218414370596192-34056.535-8640.7129-16080.6141271419511364661548227-54441.725-11022.7122-16773.13718922616921335882601219-41752.532-9434.082-12466.14215820016027495475552217-38456.544-10741.1113-16269.81914516414123354372591275-51053.939-11434.2159-21374.63116920019823305294748214-38256.044-11937.0108-15072.0281982261841826408458054-11447.418-4837.514-2360.9736434829725140147-29549.828-10626.470-9276.1251331581041817284039256-9956.610-2638.517-2373.9430344451211191392928-589649.7470-141533.21836-247974.143021532583206727548365510348162Postseason Misc TotalsseasonTeam2005-06CLE2006-07CLE2007-08CLE2008-09CLE2009-10CLE2010-11MIA2011-12MIA2012-13MIA2013-14MIA2014-15CLE2015-16CLE2016-17CLE2017-18CLE2019-20LAL2020-21LAL2022-23LAL2023-24LALCareerDD2TD3DQEJECTTECHFLAGAST/TOSTL/TOSC-EFFSH-EFF4200001.20.31.3030.518000102.40.51.2560.446100201.80.41.3310.447100002.70.61.5830.554200002.00.51.5170.558100001.90.51.3320.5111110301.60.51.3880.527310402.20.61.3800.535000201.60.61.6120.6214300102.10.41.1050.4413200002.10.71.3240.5610300202.00.51.5390.6215400102.10.31.4670.5816500102.20.31.5180.622000001.90.41.2280.559000202.60.41.3290.552000002.30.61.4040.6214128201902.00.51.3840.54Glossary3P%:3-Point Field Goal Percentage3PT:3-Point Field Goals Made-Attempted Per GameAST:Assists Per GameAST/TO:Assist To Turnover RatioBLK:Blocks Per GameDD2:Double DoubleDQ:DisqualificationsDR:Defensive Rebounds Per GameEJECT:EjectionsFG:Field Goals Made-Attempted Per GameFG%:Field Goal PercentageFLAG:Flagrant FoulsFT:Free Throws Made-Attempted Per GameFT%:Free Throw PercentageGP:Games PlayedGS:Games StartedMIN:Minutes Per GameOR:Offensive Rebounds Per GamePF:Fouls Per GamePTS:Points Per GameREB:Rebounds Per GameSC-EFF:Scoring EfficiencySH-EFF:Shooting EfficiencySTL:Steals Per GameSTL/TO:Steal To Turnover RatioTD3:Triple DoubleTECH:Technical FoulsTO:Turnovers Per GameLatest Videos1:17Would drafting Bronny James still get a team a shot at signing LeBron?Would drafting Bronny James still get a team a shot at signing LeBron?1:17Why Kendrick Perkins wishes LeBron James would retire1:41Stephen A. tantalized by the thought of LeBron on the Knicks1:43See All2023-24 Pacific StandingsTeamWLPCTGBSTRKLA Clippers5131.622-L3Phoenix4933.5982W3LA Lakers4735.5734W2Sacramento4636.5615W1Golden State4636.5615W1Terms of UsePrivacy PolicyInterest-Based AdsEU Privacy RightsCookie PolicyManage Privacy PreferencesÂ© ESPN Enterprises, Inc. All rights reserved.

In [55]:
# Trova la tabella dei dati dei postseason totals (Ã¨ la terza tabella nella pagina)
tables = pageSoup.find_all('table', class_='Table Table--align-right')
if len(tables) >= 3:  # Verifica se ci sono almeno tre tabelle nella pagina
    table = tables[1]  # Prendi la terza tabella
else:
    print("Non sono presenti abbastanza tabelle nella pagina per estrarre i postseason totals.")
    exit()

# Estrai i dati dalla tabella e crea una lista di dizionari
data = []
if table:
    rows = table.find_all('tr')
    for row in rows[1:]:  # Ignora l'intestazione
        cols = row.find_all(['th', 'td'])
        cols = [col.text.strip() for col in cols]
        data.append({
            'FG': cols[0],
            'FG%': cols[1],
            '3PT': cols[2],
            '3P%': cols[3],
            'FT': cols[4],
            'FT%': cols[5],
            'OR': cols[6],
            'DR': cols[7],
            'REB': cols[8],
            'AST': cols[9],
            'BLK': cols[10],
            'STL': cols[11],
            'TO': cols[12],
            'PTS': cols[13]
        })

# Crea un DataFrame Pandas
dfAUX1 = pd.DataFrame(data)

# Stampa il DataFrame
display(dfAUX1)

,FG,FG%,3PT,3P%,FT,FT%,OR,DR,REB,AST,BLK,STL,TO,PTS
0,146-307,47.6,21-63,33.3,87-118,73.7,22,83,105,76,9,18,44,65
1,166-399,41.6,21-75,28.0,148-196,75.5,26,135,161,159,10,34,40,66
2,113-275,41.1,18-70,25.7,122-167,73.1,16,86,102,99,17,23,33,54
3,159-312,51.0,27-81,33.3,149-199,74.9,19,109,128,102,12,23,30,38
4,106-211,50.2,20-50,40.0,88-120,73.3,15,87,102,84,20,19,23,42
5,174-373,46.6,30-85,35.3,119-156,76.3,34,142,176,123,25,35,56,66
6,251-502,50.0,22-85,25.9,173-234,73.9,54,170,224,129,16,43,47,81
7,212-432,49.1,36-96,37.5,136-175,77.7,37,156,193,152,18,41,43,70
8,192-340,56.5,35-86,40.7,129-160,80.6,14,127,141,95,11,36,46,61
9,227-544,41.7,25-110,22.7,122-167,73.1,37,189,226,169,21,33,58,82
10,219-417,52.5,32-94,34.0,82-124,66.1,42,158,200,160,27,49,54,75
11,217-384,56.5,44-107,41.1,113-162,69.8,19,145,164,141,23,35,43,72
12,275-510,53.9,39-114,34.2,159-213,74.6,31,169,200,198,23,30,52,94
13,214-382,56.0,44-119,37.0,108-150,72.0,28,198,226,184,18,26,40,84
14,54-114,47.4,18-48,37.5,14-23,60.9,7,36,43,48,2,9,7,25
15,147-295,49.8,28-106,26.4,70-92,76.1,25,133,158,104,18,17,28,40
16,56-99,56.6,10-26,38.5,17-23,73.9,4,30,34,44,5,12,11,19
17,2928-5896,49.7,470-1415,33.2,1836-2479,74.1,430,2153,2583,2067,275,483,655,1034

In [56]:
teams = ['CLE', 'MIA', 'LAL']
season = ['2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']

data = []

# Aggiunta delle tuple per CLE
for year in season[:5]:
    data.append(('CLE', year))
    
# Aggiunta delle tuple per MIA
for year in season[5:9]:
    data.append(('MIA', year))

# Aggiunta delle tuple per CLE
for year in season[9:13]:
    data.append(('CLE', year))

# Aggiunta delle tuple per LAL
for year in season[13:]:
    data.append(('LAL', year))

# Creazione del DataFrame
dfAUX2 = pd.DataFrame(data, columns=['Team', 'Season'])

# Visualizzazione del DataFrame
display(dfAUX2)

   Team   Season
0   CLE  2005-06
1   CLE  2006-07
2   CLE  2007-08
3   CLE  2008-09
4   CLE  2009-10
5   MIA  2010-11
6   MIA  2011-12
7   MIA  2012-13
8   MIA  2013-14
9   CLE  2014-15
10  CLE  2015-16
11  CLE  2016-17
12  CLE  2017-18
13  LAL  2019-20
14  LAL  2020-21
15  LAL  2021-22
16  LAL  2022-23
17  LAL  2023-24

In [57]:
dfPlayOff = dfAUX2.join(dfAUX1)
dfPlayOff.set_index(['Team', 'Season'], inplace=True)
display(dfPlayOff)

                     FG   FG%       3PT   3P%         FT   FT%   OR    DR  \
Team Season
CLE  2005-06    146-307  47.6     21-63  33.3     87-118  73.7   22    83
     2006-07    166-399  41.6     21-75  28.0    148-196  75.5   26   135
     2007-08    113-275  41.1     18-70  25.7    122-167  73.1   16    86
     2008-09    159-312  51.0     27-81  33.3    149-199  74.9   19   109
     2009-10    106-211  50.2     20-50  40.0     88-120  73.3   15    87
MIA  2010-11    174-373  46.6     30-85  35.3    119-156  76.3   34   142
     2011-12    251-502  50.0     22-85  25.9    173-234  73.9   54   170
     2012-13    212-432  49.1     36-96  37.5    136-175  77.7   37   156
     2013-14    192-340  56.5     35-86  40.7    129-160  80.6   14   127
CLE  2014-15    227-544  41.7    25-110  22.7    122-167  73.1   37   189
     2015-16    219-417  52.5     32-94  34.0     82-124  66.1   42   158
     2016-17    217-384  56.5    44-107  41.1    113-162  69.8   19   145
     2017-18    275-510  53.9    39-114  34.2    159-213  74.6   31   169
LAL  2019-20    214-382  56.0    44-119  37.0    108-150  72.0   28   198
     2020-21     54-114  47.4     18-48  37.5      14-23  60.9    7    36
     2021-22    147-295  49.8    28-106  26.4      70-92  76.1   25   133
     2022-23      56-99  56.6     10-26  38.5      17-23  73.9    4    30
     2023-24  2928-5896  49.7  470-1415  33.2  1836-2479  74.1  430  2153

               REB   AST  BLK  STL   TO   PTS
Team Season
CLE  2005-06   105    76    9   18   44    65
     2006-07   161   159   10   34   40    66
     2007-08   102    99   17   23   33    54
     2008-09   128   102   12   23   30    38
     2009-10   102    84   20   19   23    42
MIA  2010-11   176   123   25   35   56    66
     2011-12   224   129   16   43   47    81
     2012-13   193   152   18   41   43    70
     2013-14   141    95   11   36   46    61
CLE  2014-15   226   169   21   33   58    82
     2015-16   200   160   27   49   54    75
     2016-17   164   141   23   35   43    72
     2017-18   200   198   23   30   52    94
LAL  2019-20   226   184   18   26   40    84
     2020-21    43    48    2    9    7    25
     2021-22   158   104   18   17   28    40
     2022-23    34    44    5   12   11    19
     2023-24  2583  2067  275  483  655  1034

In [58]:
df = pd.read_csv('lebron_career_data.csv', encoding='utf8')

df = df.drop(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'PLAYER_AGE', 'GP', 'GS', ''], axis = 1)
df = df.rename(columns={'TEAM_ABBREVIATION': 'Team', 'FG_PCT': 'FG%'})

display(df)

,Team,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG%,FG3M,FG3A,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,CLE,19.0,79,79,3120.0,622,1492,0.417,63,217,...,0.754,99,333,432,465,130,58,273,149,1654
1,CLE,20.0,80,80,3388.0,795,1684,0.472,108,308,...,0.750,111,477,588,577,177,52,262,146,2175
2,CLE,21.0,79,79,3361.0,875,1823,0.480,127,379,...,0.738,75,481,556,521,123,66,260,181,2478
3,CLE,22.0,78,78,3190.0,772,1621,0.476,99,310,...,0.698,83,443,526,470,125,55,250,171,2132
4,CLE,23.0,75,74,3027.0,794,1642,0.484,113,359,...,0.712,133,459,592,539,138,81,255,165,2250
5,CLE,24.0,81,81,3054.0,789,1613,0.489,132,384,...,0.780,106,507,613,587,137,93,241,139,2304
6,CLE,25.0,76,76,2966.0,768,1528,0.503,129,387,...,0.767,71,483,554,651,125,77,261,119,2258
7,MIA,26.0,79,79,3063.0,758,1485,0.510,92,279,...,0.759,80,510,590,554,124,50,284,163,2111
8,MIA,27.0,62,62,2326.0,621,1169,0.531,54,149,...,0.771,94,398,492,387,115,50,213,96,1683
9,MIA,28.0,76,76,2877.0,765,1354,0.565,103,254,...,0.753,97,513,610,551,129,67,226,110,2036
10,MIA,29.0,77,77,2902.0,767,1353,0.567,116,306,...,0.750,81,452,533,488,121,26,270,126,2089
11,CLE,30.0,69,69,2493.0,624,1279,0.488,120,339,...,0.710,51,365,416,511,109,49,272,135,1743
12,CLE,31.0,76,76,2709.0,737,1416,0.520,87,282,...,0.731,111,454,565,514,104,49,249,143,1920
13,CLE,32.0,74,74,2795.0,736,1344,0.548,124,342,...,0.674,97,542,639,646,92,44,303,134,1954
14,CLE,33.0,82,82,3026.0,857,1580,0.542,149,406,...,0.731,97,612,709,747,116,71,347,136,2251
15,LAL,34.0,55,55,1937.0,558,1095,0.510,111,327,...,0.665,57,408,465,454,72,33,197,94,1505
16,LAL,35.0,67,67,2316.0,643,1303,0.493,148,425,...,0.693,66,459,525,684,78,36,261,118,1698
17,LAL,36.0,45,45,1504.0,422,823,0.513,104,285,...,0.698,29,317,346,350,48,25,168,70,1126
18,LAL,37.0,56,56,2084.0,640,1221,0.524,161,448,...,0.756,63,396,459,349,73,59,196,121,1695
19,LAL,38.0,55,54,1954.0,609,1219,0.500,121,377,...,0.768,65,392,457,375,50,32,178,88,1590
20,LAL,39.0,71,71,2504.0,685,1269,0.540,149,363,...,0.750,61,457,518,589,89,38,245,78,1822